// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xxxfields.proto

package test

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/bittorrent/protobuf/gogoproto"
	proto "github.com/bittorrent/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NativeWithSizeCache struct {
	Field1        *float64 `protobuf:"fixed64,1,opt,name=Field1" json:"Field1,omitempty" pg:"Field1"`
	Field2        *float32 `protobuf:"fixed32,2,opt,name=Field2" json:"Field2,omitempty" pg:"Field2"`
	Field3        *int32   `protobuf:"varint,3,opt,name=Field3" json:"Field3,omitempty" pg:"Field3"`
	Field4        *int64   `protobuf:"varint,4,opt,name=Field4" json:"Field4,omitempty" pg:"Field4"`
	Field11       uint64   `protobuf:"fixed64,11,opt,name=Field11" json:"Field11" pg:"Field11"`
	Field13       *bool    `protobuf:"varint,13,opt,name=Field13" json:"Field13,omitempty" pg:"Field13"`
	Field14       *string  `protobuf:"bytes,14,opt,name=Field14" json:"Field14,omitempty" pg:"Field14"`
	Field15       []byte   `protobuf:"bytes,15,opt,name=Field15" json:"Field15,omitempty" pg:"Field15"`
	XXX_sizecache int32    `json:"-" pg:"-"`
}

func (m *NativeWithSizeCache) Reset()         { *m = NativeWithSizeCache{} }
func (m *NativeWithSizeCache) String() string { return proto.CompactTextString(m) }
func (*NativeWithSizeCache) ProtoMessage()    {}
func (*NativeWithSizeCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba18cdebbd18dc5d, []int{0}
}
func (m *NativeWithSizeCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NativeWithSizeCache.Unmarshal(m, b)
}
func (m *NativeWithSizeCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NativeWithSizeCache.Marshal(b, m, deterministic)
}
func (m *NativeWithSizeCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeWithSizeCache.Merge(m, src)
}
func (m *NativeWithSizeCache) XXX_Size() int {
	return xxx_messageInfo_NativeWithSizeCache.Size(m)
}
func (m *NativeWithSizeCache) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeWithSizeCache.DiscardUnknown(m)
}

var xxx_messageInfo_NativeWithSizeCache proto.InternalMessageInfo

func (m *NativeWithSizeCache) GetField1() float64 {
	if m != nil && m.Field1 != nil {
		return *m.Field1
	}
	return 0
}

func (m *NativeWithSizeCache) GetField2() float32 {
	if m != nil && m.Field2 != nil {
		return *m.Field2
	}
	return 0
}

func (m *NativeWithSizeCache) GetField3() int32 {
	if m != nil && m.Field3 != nil {
		return *m.Field3
	}
	return 0
}

func (m *NativeWithSizeCache) GetField4() int64 {
	if m != nil && m.Field4 != nil {
		return *m.Field4
	}
	return 0
}

func (m *NativeWithSizeCache) GetField11() uint64 {
	if m != nil {
		return m.Field11
	}
	return 0
}

func (m *NativeWithSizeCache) GetField13() bool {
	if m != nil && m.Field13 != nil {
		return *m.Field13
	}
	return false
}

func (m *NativeWithSizeCache) GetField14() string {
	if m != nil && m.Field14 != nil {
		return *m.Field14
	}
	return ""
}

func (m *NativeWithSizeCache) GetField15() []byte {
	if m != nil {
		return m.Field15
	}
	return nil
}

type StructWithSizeCache struct {
	Field1        float64                `protobuf:"fixed64,1,opt,name=Field1" json:"Field1" pg:"Field1"`
	Field2        float32                `protobuf:"fixed32,2,opt,name=Field2" json:"Field2" pg:"Field2"`
	Field3        NativeWithSizeCache    `protobuf:"bytes,3,opt,name=Field3" json:"Field3" pg:"Field3"`
	Field6        *uint64                `protobuf:"varint,6,opt,name=Field6" json:"Field6,omitempty" pg:"Field6"`
	Field7        int32                  `protobuf:"zigzag32,7,opt,name=Field7" json:"Field7" pg:"Field7"`
	Field8        NativeWithoutSizeCache `protobuf:"bytes,8,opt,name=Field8" json:"Field8" pg:"Field8"`
	Field13       []bool                 `protobuf:"varint,13,rep,name=Field13" json:"Field13,omitempty" pg:"Field13"`
	Field14       *string                `protobuf:"bytes,14,opt,name=Field14" json:"Field14,omitempty" pg:"Field14"`
	Field15       []byte                 `protobuf:"bytes,15,opt,name=Field15" json:"Field15" pg:"Field15"`
	XXX_sizecache int32                  `json:"-" pg:"-"`
}

func (m *StructWithSizeCache) Reset()         { *m = StructWithSizeCache{} }
func (m *StructWithSizeCache) String() string { return proto.CompactTextString(m) }
func (*StructWithSizeCache) ProtoMessage()    {}
func (*StructWithSizeCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba18cdebbd18dc5d, []int{1}
}
func (m *StructWithSizeCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructWithSizeCache.Unmarshal(m, b)
}
func (m *StructWithSizeCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructWithSizeCache.Marshal(b, m, deterministic)
}
func (m *StructWithSizeCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructWithSizeCache.Merge(m, src)
}
func (m *StructWithSizeCache) XXX_Size() int {
	return xxx_messageInfo_StructWithSizeCache.Size(m)
}
func (m *StructWithSizeCache) XXX_DiscardUnknown() {
	xxx_messageInfo_StructWithSizeCache.DiscardUnknown(m)
}

var xxx_messageInfo_StructWithSizeCache proto.InternalMessageInfo

func (m *StructWithSizeCache) GetField1() float64 {
	if m != nil {
		return m.Field1
	}
	return 0
}

func (m *StructWithSizeCache) GetField2() float32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

func (m *StructWithSizeCache) GetField3() NativeWithSizeCache {
	if m != nil {
		return m.Field3
	}
	return NativeWithSizeCache{}
}

func (m *StructWithSizeCache) GetField6() uint64 {
	if m != nil && m.Field6 != nil {
		return *m.Field6
	}
	return 0
}

func (m *StructWithSizeCache) GetField7() int32 {
	if m != nil {
		return m.Field7
	}
	return 0
}

func (m *StructWithSizeCache) GetField8() NativeWithoutSizeCache {
	if m != nil {
		return m.Field8
	}
	return NativeWithoutSizeCache{}
}

func (m *StructWithSizeCache) GetField13() []bool {
	if m != nil {
		return m.Field13
	}
	return nil
}

func (m *StructWithSizeCache) GetField14() string {
	if m != nil && m.Field14 != nil {
		return *m.Field14
	}
	return ""
}

func (m *StructWithSizeCache) GetField15() []byte {
	if m != nil {
		return m.Field15
	}
	return nil
}

type NativeWithoutSizeCache struct {
	Field1  *float64 `protobuf:"fixed64,1,opt,name=Field1" json:"Field1,omitempty" pg:"Field1"`
	Field2  *float32 `protobuf:"fixed32,2,opt,name=Field2" json:"Field2,omitempty" pg:"Field2"`
	Field3  *int32   `protobuf:"varint,3,opt,name=Field3" json:"Field3,omitempty" pg:"Field3"`
	Field4  *int64   `protobuf:"varint,4,opt,name=Field4" json:"Field4,omitempty" pg:"Field4"`
	Field11 uint64   `protobuf:"fixed64,11,opt,name=Field11" json:"Field11" pg:"Field11"`
	Field13 *bool    `protobuf:"varint,13,opt,name=Field13" json:"Field13,omitempty" pg:"Field13"`
	Field14 *string  `protobuf:"bytes,14,opt,name=Field14" json:"Field14,omitempty" pg:"Field14"`
	Field15 []byte   `protobuf:"bytes,15,opt,name=Field15" json:"Field15,omitempty" pg:"Field15"`
}

func (m *NativeWithoutSizeCache) Reset()         { *m = NativeWithoutSizeCache{} }
func (m *NativeWithoutSizeCache) String() string { return proto.CompactTextString(m) }
func (*NativeWithoutSizeCache) ProtoMessage()    {}
func (*NativeWithoutSizeCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba18cdebbd18dc5d, []int{2}
}
func (m *NativeWithoutSizeCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NativeWithoutSizeCache.Unmarshal(m, b)
}
func (m *NativeWithoutSizeCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NativeWithoutSizeCache.Marshal(b, m, deterministic)
}
func (m *NativeWithoutSizeCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeWithoutSizeCache.Merge(m, src)
}
func (m *NativeWithoutSizeCache) XXX_Size() int {
	return xxx_messageInfo_NativeWithoutSizeCache.Size(m)
}
func (m *NativeWithoutSizeCache) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeWithoutSizeCache.DiscardUnknown(m)
}

var xxx_messageInfo_NativeWithoutSizeCache proto.InternalMessageInfo

func (m *NativeWithoutSizeCache) GetField1() float64 {
	if m != nil && m.Field1 != nil {
		return *m.Field1
	}
	return 0
}

func (m *NativeWithoutSizeCache) GetField2() float32 {
	if m != nil && m.Field2 != nil {
		return *m.Field2
	}
	return 0
}

func (m *NativeWithoutSizeCache) GetField3() int32 {
	if m != nil && m.Field3 != nil {
		return *m.Field3
	}
	return 0
}

func (m *NativeWithoutSizeCache) GetField4() int64 {
	if m != nil && m.Field4 != nil {
		return *m.Field4
	}
	return 0
}

func (m *NativeWithoutSizeCache) GetField11() uint64 {
	if m != nil {
		return m.Field11
	}
	return 0
}

func (m *NativeWithoutSizeCache) GetField13() bool {
	if m != nil && m.Field13 != nil {
		return *m.Field13
	}
	return false
}

func (m *NativeWithoutSizeCache) GetField14() string {
	if m != nil && m.Field14 != nil {
		return *m.Field14
	}
	return ""
}

func (m *NativeWithoutSizeCache) GetField15() []byte {
	if m != nil {
		return m.Field15
	}
	return nil
}

type StructWithoutSizeCache struct {
	Field1  float64                `protobuf:"fixed64,1,opt,name=Field1" json:"Field1" pg:"Field1"`
	Field2  float32                `protobuf:"fixed32,2,opt,name=Field2" json:"Field2" pg:"Field2"`
	Field3  NativeWithSizeCache    `protobuf:"bytes,3,opt,name=Field3" json:"Field3" pg:"Field3"`
	Field6  *uint64                `protobuf:"varint,6,opt,name=Field6" json:"Field6,omitempty" pg:"Field6"`
	Field7  int32                  `protobuf:"zigzag32,7,opt,name=Field7" json:"Field7" pg:"Field7"`
	Field8  NativeWithoutSizeCache `protobuf:"bytes,8,opt,name=Field8" json:"Field8" pg:"Field8"`
	Field13 []bool                 `protobuf:"varint,13,rep,name=Field13" json:"Field13,omitempty" pg:"Field13"`
	Field14 *string                `protobuf:"bytes,14,opt,name=Field14" json:"Field14,omitempty" pg:"Field14"`
	Field15 []byte                 `protobuf:"bytes,15,opt,name=Field15" json:"Field15" pg:"Field15"`
}

func (m *StructWithoutSizeCache) Reset()         { *m = StructWithoutSizeCache{} }
func (m *StructWithoutSizeCache) String() string { return proto.CompactTextString(m) }
func (*StructWithoutSizeCache) ProtoMessage()    {}
func (*StructWithoutSizeCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba18cdebbd18dc5d, []int{3}
}
func (m *StructWithoutSizeCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructWithoutSizeCache.Unmarshal(m, b)
}
func (m *StructWithoutSizeCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructWithoutSizeCache.Marshal(b, m, deterministic)
}
func (m *StructWithoutSizeCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructWithoutSizeCache.Merge(m, src)
}
func (m *StructWithoutSizeCache) XXX_Size() int {
	return xxx_messageInfo_StructWithoutSizeCache.Size(m)
}
func (m *StructWithoutSizeCache) XXX_DiscardUnknown() {
	xxx_messageInfo_StructWithoutSizeCache.DiscardUnknown(m)
}

var xxx_messageInfo_StructWithoutSizeCache proto.InternalMessageInfo

func (m *StructWithoutSizeCache) GetField1() float64 {
	if m != nil {
		return m.Field1
	}
	return 0
}

func (m *StructWithoutSizeCache) GetField2() float32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

func (m *StructWithoutSizeCache) GetField3() NativeWithSizeCache {
	if m != nil {
		return m.Field3
	}
	return NativeWithSizeCache{}
}

func (m *StructWithoutSizeCache) GetField6() uint64 {
	if m != nil && m.Field6 != nil {
		return *m.Field6
	}
	return 0
}

func (m *StructWithoutSizeCache) GetField7() int32 {
	if m != nil {
		return m.Field7
	}
	return 0
}

func (m *StructWithoutSizeCache) GetField8() NativeWithoutSizeCache {
	if m != nil {
		return m.Field8
	}
	return NativeWithoutSizeCache{}
}

func (m *StructWithoutSizeCache) GetField13() []bool {
	if m != nil {
		return m.Field13
	}
	return nil
}

func (m *StructWithoutSizeCache) GetField14() string {
	if m != nil && m.Field14 != nil {
		return *m.Field14
	}
	return ""
}

func (m *StructWithoutSizeCache) GetField15() []byte {
	if m != nil {
		return m.Field15
	}
	return nil
}

func init() {
	proto.RegisterType((*NativeWithSizeCache)(nil), "test.NativeWithSizeCache")
	proto.RegisterType((*StructWithSizeCache)(nil), "test.StructWithSizeCache")
	proto.RegisterType((*NativeWithoutSizeCache)(nil), "test.NativeWithoutSizeCache")
	proto.RegisterType((*StructWithoutSizeCache)(nil), "test.StructWithoutSizeCache")
}

func init() { proto.RegisterFile("xxxfields.proto", fileDescriptor_ba18cdebbd18dc5d) }

var fileDescriptor_ba18cdebbd18dc5d = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x52, 0x3f, 0x4f, 0xc2, 0x40,
	0x1c, 0xe5, 0x57, 0x2a, 0xe0, 0x81, 0x12, 0x4b, 0x42, 0x4e, 0x43, 0xca, 0x85, 0xe9, 0xa6, 0x12,
	0xda, 0xf2, 0x27, 0x8c, 0x98, 0x38, 0x3a, 0xc0, 0xe0, 0x0c, 0x58, 0xa0, 0x89, 0x7a, 0xa6, 0x5c,
	0x0d, 0xf1, 0x53, 0x38, 0xba, 0xca, 0xe4, 0x47, 0xf0, 0x23, 0x38, 0x3a, 0x3b, 0x98, 0xc0, 0xee,
	0xe6, 0xe0, 0x68, 0x28, 0xd7, 0xd6, 0x23, 0x0c, 0xc6, 0xd1, 0xb8, 0xf5, 0xde, 0xeb, 0xef, 0xde,
	0xbd, 0xf7, 0x7b, 0x28, 0x3f, 0x9b, 0xcd, 0x46, 0xae, 0x73, 0x71, 0x3e, 0x35, 0xae, 0x3d, 0xc6,
	0x99, 0xa6, 0x72, 0x67, 0xca, 0x8f, 0xac, 0xb1, 0xcb, 0x27, 0xfe, 0xc0, 0x18, 0xb2, 0xcb, 0xea,
	0xc0, 0xe5, 0x9c, 0x79, 0x9e, 0x73, 0xc5, 0xab, 0xc1, 0x2f, 0x03, 0x7f, 0x54, 0x1d, 0xb3, 0x31,
	0x0b, 0x0e, 0xc1, 0xd7, 0x7a, 0xb4, 0xf2, 0x0e, 0xa8, 0x70, 0xda, 0xe7, 0xee, 0x8d, 0x73, 0xe6,
	0xf2, 0x49, 0xcf, 0xbd, 0x75, 0x8e, 0xfb, 0xc3, 0x89, 0xa3, 0x15, 0x51, 0xea, 0x64, 0x25, 0x51,
	0xc3, 0x40, 0x80, 0x42, 0x57, 0x9c, 0x22, 0xdc, 0xc4, 0x0a, 0x01, 0xaa, 0x08, 0xdc, 0x8c, 0x70,
	0x0b, 0x27, 0x09, 0xd0, 0x1d, 0x81, 0x5b, 0x11, 0x6e, 0x63, 0x95, 0x00, 0x4d, 0x0a, 0xdc, 0xd6,
	0x74, 0x94, 0x5e, 0xdf, 0x58, 0xc3, 0x59, 0x02, 0x34, 0xd5, 0x51, 0x9f, 0xdf, 0xca, 0x89, 0x6e,
	0x08, 0x6a, 0x38, 0xe4, 0x2d, 0xbc, 0x47, 0x80, 0x66, 0x42, 0xc6, 0x8a, 0x19, 0x1b, 0xef, 0x13,
	0xa0, 0xbb, 0x21, 0x63, 0xc7, 0x4c, 0x1d, 0xe7, 0x09, 0xd0, 0x5c, 0xc8, 0xd4, 0xdb, 0x99, 0x97,
	0x87, 0x72, 0xe2, 0x7e, 0x5e, 0x4e, 0x54, 0x5e, 0x15, 0x54, 0xe8, 0x71, 0xcf, 0x1f, 0x72, 0xd9,
	0x6f, 0x49, 0xf6, 0x2b, 0x9e, 0x13, 0xba, 0x2e, 0xc9, 0xae, 0x25, 0xd6, 0xd4, 0x9a, 0x92, 0xf7,
	0xac, 0x79, 0x68, 0xac, 0xf6, 0x61, 0x6c, 0x89, 0x55, 0x1a, 0x8c, 0xc3, 0x69, 0xe0, 0x14, 0x01,
	0xaa, 0x0a, 0xbc, 0x11, 0xc9, 0x35, 0x71, 0x9a, 0x00, 0x3d, 0x90, 0xa6, 0x9a, 0x5a, 0x5b, 0xb0,
	0x2d, 0x9c, 0x09, 0xe4, 0x4a, 0x9b, 0x72, 0xcc, 0xe7, 0xdb, 0x15, 0x5b, 0x72, 0xac, 0xc9, 0x9f,
	0xc5, 0xaa, 0x6f, 0xc4, 0x2a, 0xaf, 0xea, 0x7b, 0xb8, 0x1f, 0x80, 0x8a, 0xdb, 0x9f, 0xf1, 0xc7,
	0xfa, 0x94, 0x5b, 0x59, 0xbe, 0x9b, 0x0b, 0xdb, 0x0b, 0x05, 0x15, 0xe3, 0x4e, 0x49, 0xb6, 0xff,
	0x6b, 0xf5, 0xeb, 0x5a, 0x49, 0x19, 0x77, 0x72, 0x9f, 0x0b, 0x1d, 0x1e, 0x97, 0x3a, 0x3c, 0x2d,
	0x75, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x29, 0xd1, 0x07, 0x51, 0x02, 0x05, 0x00, 0x00,
}

func (this *NativeWithSizeCache) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*NativeWithSizeCache)
	if !ok {
		that2, ok := that.(NativeWithSizeCache)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field1 != nil && that1.Field1 != nil {
		if *this.Field1 != *that1.Field1 {
			return false
		}
	} else if this.Field1 != nil {
		return false
	} else if that1.Field1 != nil {
		return false
	}
	if this.Field2 != nil && that1.Field2 != nil {
		if *this.Field2 != *that1.Field2 {
			return false
		}
	} else if this.Field2 != nil {
		return false
	} else if that1.Field2 != nil {
		return false
	}
	if this.Field3 != nil && that1.Field3 != nil {
		if *this.Field3 != *that1.Field3 {
			return false
		}
	} else if this.Field3 != nil {
		return false
	} else if that1.Field3 != nil {
		return false
	}
	if this.Field4 != nil && that1.Field4 != nil {
		if *this.Field4 != *that1.Field4 {
			return false
		}
	} else if this.Field4 != nil {
		return false
	} else if that1.Field4 != nil {
		return false
	}
	if this.Field11 != that1.Field11 {
		return false
	}
	if this.Field13 != nil && that1.Field13 != nil {
		if *this.Field13 != *that1.Field13 {
			return false
		}
	} else if this.Field13 != nil {
		return false
	} else if that1.Field13 != nil {
		return false
	}
	if this.Field14 != nil && that1.Field14 != nil {
		if *this.Field14 != *that1.Field14 {
			return false
		}
	} else if this.Field14 != nil {
		return false
	} else if that1.Field14 != nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *StructWithSizeCache) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StructWithSizeCache)
	if !ok {
		that2, ok := that.(StructWithSizeCache)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field1 != that1.Field1 {
		return false
	}
	if this.Field2 != that1.Field2 {
		return false
	}
	if !this.Field3.Equal(&that1.Field3) {
		return false
	}
	if this.Field6 != nil && that1.Field6 != nil {
		if *this.Field6 != *that1.Field6 {
			return false
		}
	} else if this.Field6 != nil {
		return false
	} else if that1.Field6 != nil {
		return false
	}
	if this.Field7 != that1.Field7 {
		return false
	}
	if !this.Field8.Equal(&that1.Field8) {
		return false
	}
	if len(this.Field13) != len(that1.Field13) {
		return false
	}
	for i := range this.Field13 {
		if this.Field13[i] != that1.Field13[i] {
			return false
		}
	}
	if this.Field14 != nil && that1.Field14 != nil {
		if *this.Field14 != *that1.Field14 {
			return false
		}
	} else if this.Field14 != nil {
		return false
	} else if that1.Field14 != nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *NativeWithoutSizeCache) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*NativeWithoutSizeCache)
	if !ok {
		that2, ok := that.(NativeWithoutSizeCache)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field1 != nil && that1.Field1 != nil {
		if *this.Field1 != *that1.Field1 {
			return false
		}
	} else if this.Field1 != nil {
		return false
	} else if that1.Field1 != nil {
		return false
	}
	if this.Field2 != nil && that1.Field2 != nil {
		if *this.Field2 != *that1.Field2 {
			return false
		}
	} else if this.Field2 != nil {
		return false
	} else if that1.Field2 != nil {
		return false
	}
	if this.Field3 != nil && that1.Field3 != nil {
		if *this.Field3 != *that1.Field3 {
			return false
		}
	} else if this.Field3 != nil {
		return false
	} else if that1.Field3 != nil {
		return false
	}
	if this.Field4 != nil && that1.Field4 != nil {
		if *this.Field4 != *that1.Field4 {
			return false
		}
	} else if this.Field4 != nil {
		return false
	} else if that1.Field4 != nil {
		return false
	}
	if this.Field11 != that1.Field11 {
		return false
	}
	if this.Field13 != nil && that1.Field13 != nil {
		if *this.Field13 != *that1.Field13 {
			return false
		}
	} else if this.Field13 != nil {
		return false
	} else if that1.Field13 != nil {
		return false
	}
	if this.Field14 != nil && that1.Field14 != nil {
		if *this.Field14 != *that1.Field14 {
			return false
		}
	} else if this.Field14 != nil {
		return false
	} else if that1.Field14 != nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *StructWithoutSizeCache) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StructWithoutSizeCache)
	if !ok {
		that2, ok := that.(StructWithoutSizeCache)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field1 != that1.Field1 {
		return false
	}
	if this.Field2 != that1.Field2 {
		return false
	}
	if !this.Field3.Equal(&that1.Field3) {
		return false
	}
	if this.Field6 != nil && that1.Field6 != nil {
		if *this.Field6 != *that1.Field6 {
			return false
		}
	} else if this.Field6 != nil {
		return false
	} else if that1.Field6 != nil {
		return false
	}
	if this.Field7 != that1.Field7 {
		return false
	}
	if !this.Field8.Equal(&that1.Field8) {
		return false
	}
	if len(this.Field13) != len(that1.Field13) {
		return false
	}
	for i := range this.Field13 {
		if this.Field13[i] != that1.Field13[i] {
			return false
		}
	}
	if this.Field14 != nil && that1.Field14 != nil {
		if *this.Field14 != *that1.Field14 {
			return false
		}
	} else if this.Field14 != nil {
		return false
	} else if that1.Field14 != nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func NewPopulatedNativeWithSizeCache(r randyXxxfields, easy bool) *NativeWithSizeCache {
	this := &NativeWithSizeCache{}
	if r.Intn(5) != 0 {
		v1 := float64(r.Float64())
		if r.Intn(2) == 0 {
			v1 *= -1
		}
		this.Field1 = &v1
	}
	if r.Intn(5) != 0 {
		v2 := float32(r.Float32())
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		this.Field2 = &v2
	}
	if r.Intn(5) != 0 {
		v3 := int32(r.Int31())
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		this.Field3 = &v3
	}
	if r.Intn(5) != 0 {
		v4 := int64(r.Int63())
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		this.Field4 = &v4
	}
	this.Field11 = uint64(uint64(r.Uint32()))
	if r.Intn(5) != 0 {
		v5 := bool(bool(r.Intn(2) == 0))
		this.Field13 = &v5
	}
	if r.Intn(5) != 0 {
		v6 := string(randStringXxxfields(r))
		this.Field14 = &v6
	}
	if r.Intn(5) != 0 {
		v7 := r.Intn(100)
		this.Field15 = make([]byte, v7)
		for i := 0; i < v7; i++ {
			this.Field15[i] = byte(r.Intn(256))
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedStructWithSizeCache(r randyXxxfields, easy bool) *StructWithSizeCache {
	this := &StructWithSizeCache{}
	this.Field1 = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Field1 *= -1
	}
	this.Field2 = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Field2 *= -1
	}
	v8 := NewPopulatedNativeWithSizeCache(r, easy)
	this.Field3 = *v8
	if r.Intn(5) != 0 {
		v9 := uint64(uint64(r.Uint32()))
		this.Field6 = &v9
	}
	this.Field7 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field7 *= -1
	}
	v10 := NewPopulatedNativeWithoutSizeCache(r, easy)
	this.Field8 = *v10
	if r.Intn(5) != 0 {
		v11 := r.Intn(10)
		this.Field13 = make([]bool, v11)
		for i := 0; i < v11; i++ {
			this.Field13[i] = bool(bool(r.Intn(2) == 0))
		}
	}
	if r.Intn(5) != 0 {
		v12 := string(randStringXxxfields(r))
		this.Field14 = &v12
	}
	v13 := r.Intn(100)
	this.Field15 = make([]byte, v13)
	for i := 0; i < v13; i++ {
		this.Field15[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedNativeWithoutSizeCache(r randyXxxfields, easy bool) *NativeWithoutSizeCache {
	this := &NativeWithoutSizeCache{}
	if r.Intn(5) != 0 {
		v14 := float64(r.Float64())
		if r.Intn(2) == 0 {
			v14 *= -1
		}
		this.Field1 = &v14
	}
	if r.Intn(5) != 0 {
		v15 := float32(r.Float32())
		if r.Intn(2) == 0 {
			v15 *= -1
		}
		this.Field2 = &v15
	}
	if r.Intn(5) != 0 {
		v16 := int32(r.Int31())
		if r.Intn(2) == 0 {
			v16 *= -1
		}
		this.Field3 = &v16
	}
	if r.Intn(5) != 0 {
		v17 := int64(r.Int63())
		if r.Intn(2) == 0 {
			v17 *= -1
		}
		this.Field4 = &v17
	}
	this.Field11 = uint64(uint64(r.Uint32()))
	if r.Intn(5) != 0 {
		v18 := bool(bool(r.Intn(2) == 0))
		this.Field13 = &v18
	}
	if r.Intn(5) != 0 {
		v19 := string(randStringXxxfields(r))
		this.Field14 = &v19
	}
	if r.Intn(5) != 0 {
		v20 := r.Intn(100)
		this.Field15 = make([]byte, v20)
		for i := 0; i < v20; i++ {
			this.Field15[i] = byte(r.Intn(256))
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedStructWithoutSizeCache(r randyXxxfields, easy bool) *StructWithoutSizeCache {
	this := &StructWithoutSizeCache{}
	this.Field1 = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Field1 *= -1
	}
	this.Field2 = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Field2 *= -1
	}
	v21 := NewPopulatedNativeWithSizeCache(r, easy)
	this.Field3 = *v21
	if r.Intn(5) != 0 {
		v22 := uint64(uint64(r.Uint32()))
		this.Field6 = &v22
	}
	this.Field7 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field7 *= -1
	}
	v23 := NewPopulatedNativeWithoutSizeCache(r, easy)
	this.Field8 = *v23
	if r.Intn(5) != 0 {
		v24 := r.Intn(10)
		this.Field13 = make([]bool, v24)
		for i := 0; i < v24; i++ {
			this.Field13[i] = bool(bool(r.Intn(2) == 0))
		}
	}
	if r.Intn(5) != 0 {
		v25 := string(randStringXxxfields(r))
		this.Field14 = &v25
	}
	v26 := r.Intn(100)
	this.Field15 = make([]byte, v26)
	for i := 0; i < v26; i++ {
		this.Field15[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyXxxfields interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneXxxfields(r randyXxxfields) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringXxxfields(r randyXxxfields) string {
	v27 := r.Intn(100)
	tmps := make([]rune, v27)
	for i := 0; i < v27; i++ {
		tmps[i] = randUTF8RuneXxxfields(r)
	}
	return string(tmps)
}
func randUnrecognizedXxxfields(r randyXxxfields, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldXxxfields(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldXxxfields(dAtA []byte, r randyXxxfields, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(key))
		v28 := r.Int63()
		if r.Intn(2) == 0 {
			v28 *= -1
		}
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(v28))
	case 1:
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateXxxfields(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateXxxfields(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
