// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: import_public/sub/a.proto

package sub

import (
	fmt "fmt"
	proto "github.com/bittorrent/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type E int32

const (
	E_ZERO E = 0
)

var E_name = map[int32]string{
	0: "ZERO",
}

var E_value = map[string]int32{
	"ZERO": 0,
}

func (x E) Enum() *E {
	p := new(E)
	*p = x
	return p
}

func (x E) String() string {
	return proto.EnumName(E_name, int32(x))
}

func (x *E) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(E_value, data, "E")
	if err != nil {
		return err
	}
	*x = E(value)
	return nil
}

func (E) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0}
}

type M_Subenum int32

const (
	M_M_ZERO M_Subenum = 0
)

var M_Subenum_name = map[int32]string{
	0: "M_ZERO",
}

var M_Subenum_value = map[string]int32{
	"M_ZERO": 0,
}

func (x M_Subenum) Enum() *M_Subenum {
	p := new(M_Subenum)
	*p = x
	return p
}

func (x M_Subenum) String() string {
	return proto.EnumName(M_Subenum_name, int32(x))
}

func (x *M_Subenum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(M_Subenum_value, data, "M_Subenum")
	if err != nil {
		return err
	}
	*x = M_Subenum(value)
	return nil
}

func (M_Subenum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0, 0}
}

type M_Submessage_Submessage_Subenum int32

const (
	M_Submessage_M_SUBMESSAGE_ZERO M_Submessage_Submessage_Subenum = 0
)

var M_Submessage_Submessage_Subenum_name = map[int32]string{
	0: "M_SUBMESSAGE_ZERO",
}

var M_Submessage_Submessage_Subenum_value = map[string]int32{
	"M_SUBMESSAGE_ZERO": 0,
}

func (x M_Submessage_Submessage_Subenum) Enum() *M_Submessage_Submessage_Subenum {
	p := new(M_Submessage_Submessage_Subenum)
	*p = x
	return p
}

func (x M_Submessage_Submessage_Subenum) String() string {
	return proto.EnumName(M_Submessage_Submessage_Subenum_name, int32(x))
}

func (x *M_Submessage_Submessage_Subenum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(M_Submessage_Submessage_Subenum_value, data, "M_Submessage_Submessage_Subenum")
	if err != nil {
		return err
	}
	*x = M_Submessage_Submessage_Subenum(value)
	return nil
}

func (M_Submessage_Submessage_Subenum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0, 1, 0}
}

type M struct {
	// Field using a type in the same Go package, but a different source file.
	M2 *M2 `protobuf:"bytes,1,opt,name=m2" json:"m2,omitempty" pg:"m2"`
	// Types that are valid to be assigned to OneofField:
	//	*M_OneofInt32
	//	*M_OneofInt64
	OneofField           isM_OneofField `protobuf_oneof:"oneof_field"`
	Grouping             *M_Grouping    `protobuf:"group,4,opt,name=Grouping,json=grouping" json:"grouping,omitempty" pg:"grouping"`
	DefaultField         *string        `protobuf:"bytes,6,opt,name=default_field,json=defaultField,def=def" json:"default_field,omitempty" pg:"default_field"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-" pg:"-"`
	XXX_unrecognized     []byte         `json:"-" pg:"-"`
	XXX_sizecache        int32          `json:"-" pg:"-"`
}

func (m *M) Reset()         { *m = M{} }
func (m *M) String() string { return proto.CompactTextString(m) }
func (*M) ProtoMessage()    {}
func (*M) Descriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0}
}
func (m *M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M.Unmarshal(m, b)
}
func (m *M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M.Marshal(b, m, deterministic)
}
func (m *M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M.Merge(m, src)
}
func (m *M) XXX_Size() int {
	return xxx_messageInfo_M.Size(m)
}
func (m *M) XXX_DiscardUnknown() {
	xxx_messageInfo_M.DiscardUnknown(m)
}

var xxx_messageInfo_M proto.InternalMessageInfo

const Default_M_DefaultField string = "def"

type isM_OneofField interface {
	isM_OneofField()
}

type M_OneofInt32 struct {
	OneofInt32 int32 `protobuf:"varint,2,opt,name=oneof_int32,json=oneofInt32,oneof" json:"oneof_int32,omitempty" pg:"oneof_int32"`
}
type M_OneofInt64 struct {
	OneofInt64 int64 `protobuf:"varint,3,opt,name=oneof_int64,json=oneofInt64,oneof" json:"oneof_int64,omitempty" pg:"oneof_int64"`
}

func (*M_OneofInt32) isM_OneofField() {}
func (*M_OneofInt64) isM_OneofField() {}

func (m *M) GetOneofField() isM_OneofField {
	if m != nil {
		return m.OneofField
	}
	return nil
}

func (m *M) GetM2() *M2 {
	if m != nil {
		return m.M2
	}
	return nil
}

func (m *M) GetOneofInt32() int32 {
	if x, ok := m.GetOneofField().(*M_OneofInt32); ok {
		return x.OneofInt32
	}
	return 0
}

func (m *M) GetOneofInt64() int64 {
	if x, ok := m.GetOneofField().(*M_OneofInt64); ok {
		return x.OneofInt64
	}
	return 0
}

func (m *M) GetGrouping() *M_Grouping {
	if m != nil {
		return m.Grouping
	}
	return nil
}

func (m *M) GetDefaultField() string {
	if m != nil && m.DefaultField != nil {
		return *m.DefaultField
	}
	return Default_M_DefaultField
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*M) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*M_OneofInt32)(nil),
		(*M_OneofInt64)(nil),
	}
}

type M_Grouping struct {
	GroupField           *string  `protobuf:"bytes,5,opt,name=group_field,json=groupField" json:"group_field,omitempty" pg:"group_field"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" pg:"-"`
	XXX_unrecognized     []byte   `json:"-" pg:"-"`
	XXX_sizecache        int32    `json:"-" pg:"-"`
}

func (m *M_Grouping) Reset()         { *m = M_Grouping{} }
func (m *M_Grouping) String() string { return proto.CompactTextString(m) }
func (*M_Grouping) ProtoMessage()    {}
func (*M_Grouping) Descriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0, 0}
}
func (m *M_Grouping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M_Grouping.Unmarshal(m, b)
}
func (m *M_Grouping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M_Grouping.Marshal(b, m, deterministic)
}
func (m *M_Grouping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M_Grouping.Merge(m, src)
}
func (m *M_Grouping) XXX_Size() int {
	return xxx_messageInfo_M_Grouping.Size(m)
}
func (m *M_Grouping) XXX_DiscardUnknown() {
	xxx_messageInfo_M_Grouping.DiscardUnknown(m)
}

var xxx_messageInfo_M_Grouping proto.InternalMessageInfo

func (m *M_Grouping) GetGroupField() string {
	if m != nil && m.GroupField != nil {
		return *m.GroupField
	}
	return ""
}

type M_Submessage struct {
	// Types that are valid to be assigned to SubmessageOneofField:
	//	*M_Submessage_SubmessageOneofInt32
	//	*M_Submessage_SubmessageOneofInt64
	SubmessageOneofField isM_Submessage_SubmessageOneofField `protobuf_oneof:"submessage_oneof_field"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-" pg:"-"`
	XXX_unrecognized     []byte                              `json:"-" pg:"-"`
	XXX_sizecache        int32                               `json:"-" pg:"-"`
}

func (m *M_Submessage) Reset()         { *m = M_Submessage{} }
func (m *M_Submessage) String() string { return proto.CompactTextString(m) }
func (*M_Submessage) ProtoMessage()    {}
func (*M_Submessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_382f7805394b5c4e, []int{0, 1}
}
func (m *M_Submessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M_Submessage.Unmarshal(m, b)
}
func (m *M_Submessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M_Submessage.Marshal(b, m, deterministic)
}
func (m *M_Submessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M_Submessage.Merge(m, src)
}
func (m *M_Submessage) XXX_Size() int {
	return xxx_messageInfo_M_Submessage.Size(m)
}
func (m *M_Submessage) XXX_DiscardUnknown() {
	xxx_messageInfo_M_Submessage.DiscardUnknown(m)
}

var xxx_messageInfo_M_Submessage proto.InternalMessageInfo

type isM_Submessage_SubmessageOneofField interface {
	isM_Submessage_SubmessageOneofField()
}

type M_Submessage_SubmessageOneofInt32 struct {
	SubmessageOneofInt32 int32 `protobuf:"varint,1,opt,name=submessage_oneof_int32,json=submessageOneofInt32,oneof" json:"submessage_oneof_int32,omitempty" pg:"submessage_oneof_int32"`
}
type M_Submessage_SubmessageOneofInt64 struct {
	SubmessageOneofInt64 int64 `protobuf:"varint,2,opt,name=submessage_oneof_int64,json=submessageOneofInt64,oneof" json:"submessage_oneof_int64,omitempty" pg:"submessage_oneof_int64"`
}

func (*M_Submessage_SubmessageOneofInt32) isM_Submessage_SubmessageOneofField() {}
func (*M_Submessage_SubmessageOneofInt64) isM_Submessage_SubmessageOneofField() {}

func (m *M_Submessage) GetSubmessageOneofField() isM_Submessage_SubmessageOneofField {
	if m != nil {
		return m.SubmessageOneofField
	}
	return nil
}

func (m *M_Submessage) GetSubmessageOneofInt32() int32 {
	if x, ok := m.GetSubmessageOneofField().(*M_Submessage_SubmessageOneofInt32); ok {
		return x.SubmessageOneofInt32
	}
	return 0
}

func (m *M_Submessage) GetSubmessageOneofInt64() int64 {
	if x, ok := m.GetSubmessageOneofField().(*M_Submessage_SubmessageOneofInt64); ok {
		return x.SubmessageOneofInt64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*M_Submessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*M_Submessage_SubmessageOneofInt32)(nil),
		(*M_Submessage_SubmessageOneofInt64)(nil),
	}
}

var E_ExtensionField = &proto.ExtensionDesc{
	ExtendedType:  (*M2)(nil),
	ExtensionType: (*string)(nil),
	Field:         1,
	Name:          "goproto.test.import_public.sub.extension_field",
	Tag:           "bytes,1,opt,name=extension_field",
	Filename:      "import_public/sub/a.proto",
}

func init() {
	proto.RegisterEnum("goproto.test.import_public.sub.E", E_name, E_value)
	proto.RegisterEnum("goproto.test.import_public.sub.M_Subenum", M_Subenum_name, M_Subenum_value)
	proto.RegisterEnum("goproto.test.import_public.sub.M_Submessage_Submessage_Subenum", M_Submessage_Submessage_Subenum_name, M_Submessage_Submessage_Subenum_value)
	proto.RegisterType((*M)(nil), "goproto.test.import_public.sub.M")
	proto.RegisterType((*M_Grouping)(nil), "goproto.test.import_public.sub.M.Grouping")
	proto.RegisterType((*M_Submessage)(nil), "goproto.test.import_public.sub.M.Submessage")
	proto.RegisterExtension(E_ExtensionField)
}

func init() { proto.RegisterFile("import_public/sub/a.proto", fileDescriptor_382f7805394b5c4e) }

var fileDescriptor_382f7805394b5c4e = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xab, 0x24, 0xed, 0xd2, 0x93, 0x65, 0x7f, 0xc4, 0x3a, 0xbc, 0x5e, 0x6c, 0x5e, 0xae,
	0x4c, 0x4b, 0x65, 0xf0, 0x82, 0x2f, 0x7a, 0xb7, 0x40, 0xda, 0x95, 0x62, 0x0a, 0x36, 0xbb, 0xe9,
	0x8d, 0xb1, 0x12, 0x59, 0x13, 0xc4, 0x92, 0xb1, 0x25, 0xd8, 0x23, 0xec, 0xbd, 0xf6, 0x62, 0xc3,
	0xb2, 0x9d, 0x34, 0x2c, 0xfb, 0x73, 0x27, 0x9f, 0xf3, 0xfd, 0xce, 0xc7, 0xf9, 0x7c, 0xe0, 0x9d,
	0x28, 0x4a, 0x55, 0xe9, 0xb4, 0x34, 0x74, 0x23, 0x56, 0x7e, 0x6d, 0xa8, 0x9f, 0x91, 0xb2, 0x52,
	0x5a, 0xe1, 0xf7, 0x5c, 0xd9, 0x07, 0xd1, 0xac, 0xd6, 0x64, 0x4f, 0x47, 0x6a, 0x43, 0xcf, 0x0f,
	0xa0, 0xb4, 0x45, 0x67, 0x3f, 0x46, 0x80, 0x22, 0x1c, 0xc0, 0xa0, 0x08, 0x1c, 0xe4, 0x22, 0x6f,
	0x12, 0xcc, 0xc8, 0xdf, 0xa7, 0x91, 0x28, 0x88, 0x07, 0x45, 0x80, 0x3f, 0xc2, 0x44, 0x49, 0xa6,
	0xf2, 0x54, 0x48, 0xfd, 0x29, 0x70, 0x06, 0x2e, 0xf2, 0x8e, 0xbf, 0x1c, 0xc5, 0x60, 0x8b, 0x77,
	0x4d, 0x6d, 0x4f, 0x12, 0xce, 0x9d, 0xa1, 0x8b, 0xbc, 0xe1, 0x53, 0x49, 0x38, 0xc7, 0x37, 0x30,
	0xe6, 0x95, 0x32, 0xa5, 0x90, 0xdc, 0x19, 0xb9, 0xc8, 0x83, 0xe0, 0xe2, 0x9f, 0xfe, 0xe4, 0xb6,
	0x23, 0xe2, 0x2d, 0x8b, 0x3d, 0x98, 0xae, 0x59, 0x9e, 0x99, 0x8d, 0x4e, 0x73, 0xc1, 0x36, 0x6b,
	0xe7, 0xc4, 0x45, 0xde, 0xe9, 0xf5, 0x70, 0xcd, 0xf2, 0xf8, 0x79, 0xd7, 0xb9, 0x69, 0x1a, 0xe7,
	0x97, 0x30, 0xee, 0x79, 0xfc, 0x01, 0x26, 0x76, 0x42, 0xc7, 0x1c, 0x37, 0x4c, 0x0c, 0xb6, 0xd4,
	0x8a, 0x7f, 0x22, 0x80, 0xc4, 0xd0, 0x82, 0xd5, 0x75, 0xc6, 0x19, 0x0e, 0xe1, 0x6d, 0xbd, 0xfd,
	0x4a, 0x9f, 0xae, 0x8f, 0xba, 0xf5, 0xdf, 0xec, 0xfa, 0x0f, 0xbb, 0x20, 0xfe, 0xc0, 0x85, 0x73,
	0x1b, 0xdb, 0xf0, 0x30, 0x17, 0xce, 0x67, 0x97, 0x80, 0x77, 0xee, 0x69, 0x62, 0x28, 0x93, 0xa6,
	0xc0, 0x67, 0xf0, 0x3a, 0x4a, 0x93, 0xaf, 0x8b, 0x68, 0x99, 0x24, 0x9f, 0x6f, 0x97, 0xe9, 0xe3,
	0x32, 0x7e, 0x78, 0x75, 0xb4, 0x70, 0x0e, 0x98, 0xd8, 0xbd, 0x66, 0x67, 0xf0, 0xac, 0x67, 0x01,
	0x4e, 0xa2, 0x1e, 0x98, 0xf6, 0xbf, 0xc7, 0xaa, 0x2e, 0xa6, 0x80, 0x96, 0x78, 0x0c, 0xa3, 0xb6,
	0x7b, 0x7d, 0x0f, 0x2f, 0xd9, 0x77, 0xcd, 0x64, 0x2d, 0x94, 0x6c, 0x15, 0xf8, 0x3f, 0x4e, 0xc3,
	0x06, 0x71, 0x1a, 0xbf, 0xd8, 0xa2, 0x36, 0xc7, 0xc5, 0xfd, 0xe3, 0x1d, 0x17, 0xfa, 0x9b, 0xa1,
	0x64, 0xa5, 0x0a, 0x9f, 0x0a, 0xad, 0x55, 0x55, 0x31, 0xa9, 0x7d, 0x3b, 0x8e, 0x9a, 0xbc, 0x7d,
	0xac, 0xae, 0x38, 0x93, 0x57, 0x5c, 0x71, 0xe5, 0x37, 0x0e, 0xeb, 0x4c, 0x67, 0xfe, 0x6f, 0xb7,
	0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x61, 0x76, 0x18, 0x0a, 0x03, 0x00, 0x00,
}
