// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: my_test/test.proto

// This package holds interesting messages.

package test

import (
	fmt "fmt"
	proto "github.com/tron-us/protobuf/proto"
	_ "github.com/tron-us/protobuf/protoc-gen-gogo/testdata/multi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HatType int32

const (
	// deliberately skipping 0
	HatType_FEDORA HatType = 1
	HatType_FEZ    HatType = 2
)

var HatType_name = map[int32]string{
	1: "FEDORA",
	2: "FEZ",
}

var HatType_value = map[string]int32{
	"FEDORA": 1,
	"FEZ":    2,
}

func (x HatType) Enum() *HatType {
	p := new(HatType)
	*p = x
	return p
}

func (x HatType) String() string {
	return proto.EnumName(HatType_name, int32(x))
}

func (x *HatType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HatType_value, data, "HatType")
	if err != nil {
		return err
	}
	*x = HatType(value)
	return nil
}

func (HatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{0}
}

// This enum represents days of the week.
type Days int32

const (
	Days_MONDAY  Days = 1
	Days_TUESDAY Days = 2
	Days_LUNDI   Days = 1
)

var Days_name = map[int32]string{
	1: "MONDAY",
	2: "TUESDAY",
	// Duplicate value: 1: "LUNDI",
}

var Days_value = map[string]int32{
	"MONDAY":  1,
	"TUESDAY": 2,
	"LUNDI":   1,
}

func (x Days) Enum() *Days {
	p := new(Days)
	*p = x
	return p
}

func (x Days) String() string {
	return proto.EnumName(Days_name, int32(x))
}

func (x *Days) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Days_value, data, "Days")
	if err != nil {
		return err
	}
	*x = Days(value)
	return nil
}

func (Days) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{1}
}

type Request_Color int32

const (
	Request_RED   Request_Color = 0
	Request_GREEN Request_Color = 1
	Request_BLUE  Request_Color = 2
)

var Request_Color_name = map[int32]string{
	0: "RED",
	1: "GREEN",
	2: "BLUE",
}

var Request_Color_value = map[string]int32{
	"RED":   0,
	"GREEN": 1,
	"BLUE":  2,
}

func (x Request_Color) Enum() *Request_Color {
	p := new(Request_Color)
	*p = x
	return p
}

func (x Request_Color) String() string {
	return proto.EnumName(Request_Color_name, int32(x))
}

func (x *Request_Color) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Request_Color_value, data, "Request_Color")
	if err != nil {
		return err
	}
	*x = Request_Color(value)
	return nil
}

func (Request_Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{0, 0}
}

type Reply_Entry_Game int32

const (
	Reply_Entry_FOOTBALL Reply_Entry_Game = 1
	Reply_Entry_TENNIS   Reply_Entry_Game = 2
)

var Reply_Entry_Game_name = map[int32]string{
	1: "FOOTBALL",
	2: "TENNIS",
}

var Reply_Entry_Game_value = map[string]int32{
	"FOOTBALL": 1,
	"TENNIS":   2,
}

func (x Reply_Entry_Game) Enum() *Reply_Entry_Game {
	p := new(Reply_Entry_Game)
	*p = x
	return p
}

func (x Reply_Entry_Game) String() string {
	return proto.EnumName(Reply_Entry_Game_name, int32(x))
}

func (x *Reply_Entry_Game) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Reply_Entry_Game_value, data, "Reply_Entry_Game")
	if err != nil {
		return err
	}
	*x = Reply_Entry_Game(value)
	return nil
}

func (Reply_Entry_Game) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{1, 0, 0}
}

// This is a message that might be sent somewhere.
type Request struct {
	Key []int64 `protobuf:"varint,1,rep,name=key" json:"key,omitempty" pg:"key"`
	//  optional imp.ImportedMessage imported_message = 2;
	Hue *Request_Color `protobuf:"varint,3,opt,name=hue,enum=my.test.Request_Color" json:"hue,omitempty" pg:"hue"`
	Hat *HatType       `protobuf:"varint,4,opt,name=hat,enum=my.test.HatType,def=1" json:"hat,omitempty" pg:"hat"`
	//  optional imp.ImportedMessage.Owner owner = 6;
	Deadline  *float32           `protobuf:"fixed32,7,opt,name=deadline,def=inf" json:"deadline,omitempty" pg:"deadline"`
	Somegroup *Request_SomeGroup `protobuf:"group,8,opt,name=SomeGroup,json=somegroup" json:"somegroup,omitempty" pg:"somegroup"`
	// This is a map field. It will generate map[int32]string.
	NameMapping map[int32]string `protobuf:"bytes,14,rep,name=name_mapping,json=nameMapping" json:"name_mapping,omitempty" pg:"name_mapping" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// This is a map field whose value type is a message.
	MsgMapping map[int64]*Reply `protobuf:"bytes,15,rep,name=msg_mapping,json=msgMapping" json:"msg_mapping,omitempty" pg:"msg_mapping" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reset_     *int32           `protobuf:"varint,12,opt,name=reset" json:"reset,omitempty" pg:"reset"`
	// This field should not conflict with any getters.
	GetKey_              *string  `protobuf:"bytes,16,opt,name=get_key,json=getKey" json:"get_key,omitempty" pg:"get_key"`
	FloatNinf            *float32 `protobuf:"fixed32,20,opt,name=float_ninf,json=floatNinf,def=-inf" json:"float_ninf,omitempty" pg:"float_ninf"`
	FloatPinf            *float32 `protobuf:"fixed32,21,opt,name=float_pinf,json=floatPinf,def=inf" json:"float_pinf,omitempty" pg:"float_pinf"`
	FloatExp             *float32 `protobuf:"fixed32,22,opt,name=float_exp,json=floatExp,def=1e+09" json:"float_exp,omitempty" pg:"float_exp"`
	DoubleNinf           *float64 `protobuf:"fixed64,23,opt,name=double_ninf,json=doubleNinf,def=-inf" json:"double_ninf,omitempty" pg:"double_ninf"`
	DoublePinf           *float64 `protobuf:"fixed64,24,opt,name=double_pinf,json=doublePinf,def=inf" json:"double_pinf,omitempty" pg:"double_pinf"`
	DoubleExp            *float64 `protobuf:"fixed64,25,opt,name=double_exp,json=doubleExp,def=1e+09" json:"double_exp,omitempty" pg:"double_exp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

const Default_Request_Hat HatType = HatType_FEDORA

var Default_Request_Deadline float32 = float32(math.Inf(1))
var Default_Request_FloatNinf float32 = float32(math.Inf(-1))
var Default_Request_FloatPinf float32 = float32(math.Inf(1))

const Default_Request_FloatExp float32 = 1e+09

var Default_Request_DoubleNinf float64 = math.Inf(-1)
var Default_Request_DoublePinf float64 = math.Inf(1)

const Default_Request_DoubleExp float64 = 1e+09

func (m *Request) GetKey() []int64 {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Request) GetHue() Request_Color {
	if m != nil && m.Hue != nil {
		return *m.Hue
	}
	return Request_RED
}

func (m *Request) GetHat() HatType {
	if m != nil && m.Hat != nil {
		return *m.Hat
	}
	return Default_Request_Hat
}

func (m *Request) GetDeadline() float32 {
	if m != nil && m.Deadline != nil {
		return *m.Deadline
	}
	return Default_Request_Deadline
}

func (m *Request) GetSomegroup() *Request_SomeGroup {
	if m != nil {
		return m.Somegroup
	}
	return nil
}

func (m *Request) GetNameMapping() map[int32]string {
	if m != nil {
		return m.NameMapping
	}
	return nil
}

func (m *Request) GetMsgMapping() map[int64]*Reply {
	if m != nil {
		return m.MsgMapping
	}
	return nil
}

func (m *Request) GetReset_() int32 {
	if m != nil && m.Reset_ != nil {
		return *m.Reset_
	}
	return 0
}

func (m *Request) GetGetKey_() string {
	if m != nil && m.GetKey_ != nil {
		return *m.GetKey_
	}
	return ""
}

func (m *Request) GetFloatNinf() float32 {
	if m != nil && m.FloatNinf != nil {
		return *m.FloatNinf
	}
	return Default_Request_FloatNinf
}

func (m *Request) GetFloatPinf() float32 {
	if m != nil && m.FloatPinf != nil {
		return *m.FloatPinf
	}
	return Default_Request_FloatPinf
}

func (m *Request) GetFloatExp() float32 {
	if m != nil && m.FloatExp != nil {
		return *m.FloatExp
	}
	return Default_Request_FloatExp
}

func (m *Request) GetDoubleNinf() float64 {
	if m != nil && m.DoubleNinf != nil {
		return *m.DoubleNinf
	}
	return Default_Request_DoubleNinf
}

func (m *Request) GetDoublePinf() float64 {
	if m != nil && m.DoublePinf != nil {
		return *m.DoublePinf
	}
	return Default_Request_DoublePinf
}

func (m *Request) GetDoubleExp() float64 {
	if m != nil && m.DoubleExp != nil {
		return *m.DoubleExp
	}
	return Default_Request_DoubleExp
}

type Request_SomeGroup struct {
	GroupField           *int32   `protobuf:"varint,9,opt,name=group_field,json=groupField" json:"group_field,omitempty" pg:"group_field"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_SomeGroup) Reset()         { *m = Request_SomeGroup{} }
func (m *Request_SomeGroup) String() string { return proto.CompactTextString(m) }
func (*Request_SomeGroup) ProtoMessage()    {}
func (*Request_SomeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{0, 0}
}
func (m *Request_SomeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_SomeGroup.Unmarshal(m, b)
}
func (m *Request_SomeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_SomeGroup.Marshal(b, m, deterministic)
}
func (m *Request_SomeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_SomeGroup.Merge(m, src)
}
func (m *Request_SomeGroup) XXX_Size() int {
	return xxx_messageInfo_Request_SomeGroup.Size(m)
}
func (m *Request_SomeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_SomeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_Request_SomeGroup proto.InternalMessageInfo

func (m *Request_SomeGroup) GetGroupField() int32 {
	if m != nil && m.GroupField != nil {
		return *m.GroupField
	}
	return 0
}

type Reply struct {
	Found                        []*Reply_Entry `protobuf:"bytes,1,rep,name=found" json:"found,omitempty" pg:"found"`
	CompactKeys                  []int32        `protobuf:"varint,2,rep,packed,name=compact_keys,json=compactKeys" json:"compact_keys,omitempty" pg:"compact_keys"`
	XXX_NoUnkeyedLiteral         struct{}       `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{1}
}

var extRange_Reply = []proto.ExtensionRange{
	{Start: 100, End: 536870911},
}

func (*Reply) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Reply
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetFound() []*Reply_Entry {
	if m != nil {
		return m.Found
	}
	return nil
}

func (m *Reply) GetCompactKeys() []int32 {
	if m != nil {
		return m.CompactKeys
	}
	return nil
}

type Reply_Entry struct {
	KeyThatNeeds_1234Camel_CasIng *int64   `protobuf:"varint,1,req,name=key_that_needs_1234camel_CasIng,json=keyThatNeeds1234camelCasIng" json:"key_that_needs_1234camel_CasIng,omitempty" pg:"key_that_needs_1234camel_CasIng"`
	Value                         *int64   `protobuf:"varint,2,opt,name=value,def=7" json:"value,omitempty" pg:"value"`
	XMyFieldName_2                *int64   `protobuf:"varint,3,opt,name=_my_field_name_2,json=MyFieldName2" json:"_my_field_name_2,omitempty" pg:"_my_field_name_2"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *Reply_Entry) Reset()         { *m = Reply_Entry{} }
func (m *Reply_Entry) String() string { return proto.CompactTextString(m) }
func (*Reply_Entry) ProtoMessage()    {}
func (*Reply_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{1, 0}
}
func (m *Reply_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply_Entry.Unmarshal(m, b)
}
func (m *Reply_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply_Entry.Marshal(b, m, deterministic)
}
func (m *Reply_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply_Entry.Merge(m, src)
}
func (m *Reply_Entry) XXX_Size() int {
	return xxx_messageInfo_Reply_Entry.Size(m)
}
func (m *Reply_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Reply_Entry proto.InternalMessageInfo

const Default_Reply_Entry_Value int64 = 7

func (m *Reply_Entry) GetKeyThatNeeds_1234Camel_CasIng() int64 {
	if m != nil && m.KeyThatNeeds_1234Camel_CasIng != nil {
		return *m.KeyThatNeeds_1234Camel_CasIng
	}
	return 0
}

func (m *Reply_Entry) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return Default_Reply_Entry_Value
}

func (m *Reply_Entry) GetXMyFieldName_2() int64 {
	if m != nil && m.XMyFieldName_2 != nil {
		return *m.XMyFieldName_2
	}
	return 0
}

type OtherBase struct {
	Name                         *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" pg:"name"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *OtherBase) Reset()         { *m = OtherBase{} }
func (m *OtherBase) String() string { return proto.CompactTextString(m) }
func (*OtherBase) ProtoMessage()    {}
func (*OtherBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{2}
}

var extRange_OtherBase = []proto.ExtensionRange{
	{Start: 100, End: 536870911},
}

func (*OtherBase) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OtherBase
}

func (m *OtherBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherBase.Unmarshal(m, b)
}
func (m *OtherBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherBase.Marshal(b, m, deterministic)
}
func (m *OtherBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherBase.Merge(m, src)
}
func (m *OtherBase) XXX_Size() int {
	return xxx_messageInfo_OtherBase.Size(m)
}
func (m *OtherBase) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherBase.DiscardUnknown(m)
}

var xxx_messageInfo_OtherBase proto.InternalMessageInfo

func (m *OtherBase) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ReplyExtensions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyExtensions) Reset()         { *m = ReplyExtensions{} }
func (m *ReplyExtensions) String() string { return proto.CompactTextString(m) }
func (*ReplyExtensions) ProtoMessage()    {}
func (*ReplyExtensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{3}
}
func (m *ReplyExtensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyExtensions.Unmarshal(m, b)
}
func (m *ReplyExtensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyExtensions.Marshal(b, m, deterministic)
}
func (m *ReplyExtensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyExtensions.Merge(m, src)
}
func (m *ReplyExtensions) XXX_Size() int {
	return xxx_messageInfo_ReplyExtensions.Size(m)
}
func (m *ReplyExtensions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyExtensions.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyExtensions proto.InternalMessageInfo

var E_ReplyExtensions_Time = &proto.ExtensionDesc{
	ExtendedType:  (*Reply)(nil),
	ExtensionType: (*float64)(nil),
	Field:         101,
	Name:          "my.test.ReplyExtensions.time",
	Tag:           "fixed64,101,opt,name=time",
	Filename:      "my_test/test.proto",
}

var E_ReplyExtensions_Carrot = &proto.ExtensionDesc{
	ExtendedType:  (*Reply)(nil),
	ExtensionType: (*ReplyExtensions)(nil),
	Field:         105,
	Name:          "my.test.ReplyExtensions.carrot",
	Tag:           "bytes,105,opt,name=carrot",
	Filename:      "my_test/test.proto",
}

var E_ReplyExtensions_Donut = &proto.ExtensionDesc{
	ExtendedType:  (*OtherBase)(nil),
	ExtensionType: (*ReplyExtensions)(nil),
	Field:         101,
	Name:          "my.test.ReplyExtensions.donut",
	Tag:           "bytes,101,opt,name=donut",
	Filename:      "my_test/test.proto",
}

type OtherReplyExtensions struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty" pg:"key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtherReplyExtensions) Reset()         { *m = OtherReplyExtensions{} }
func (m *OtherReplyExtensions) String() string { return proto.CompactTextString(m) }
func (*OtherReplyExtensions) ProtoMessage()    {}
func (*OtherReplyExtensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{4}
}
func (m *OtherReplyExtensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherReplyExtensions.Unmarshal(m, b)
}
func (m *OtherReplyExtensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherReplyExtensions.Marshal(b, m, deterministic)
}
func (m *OtherReplyExtensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherReplyExtensions.Merge(m, src)
}
func (m *OtherReplyExtensions) XXX_Size() int {
	return xxx_messageInfo_OtherReplyExtensions.Size(m)
}
func (m *OtherReplyExtensions) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherReplyExtensions.DiscardUnknown(m)
}

var xxx_messageInfo_OtherReplyExtensions proto.InternalMessageInfo

func (m *OtherReplyExtensions) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

type OldReply struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `protobuf_messageset:"1" json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *OldReply) Reset()         { *m = OldReply{} }
func (m *OldReply) String() string { return proto.CompactTextString(m) }
func (*OldReply) ProtoMessage()    {}
func (*OldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{5}
}

var extRange_OldReply = []proto.ExtensionRange{
	{Start: 100, End: 2147483646},
}

func (*OldReply) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OldReply
}

func (m *OldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OldReply.Unmarshal(m, b)
}
func (m *OldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OldReply.Marshal(b, m, deterministic)
}
func (m *OldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OldReply.Merge(m, src)
}
func (m *OldReply) XXX_Size() int {
	return xxx_messageInfo_OldReply.Size(m)
}
func (m *OldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OldReply.DiscardUnknown(m)
}

var xxx_messageInfo_OldReply proto.InternalMessageInfo

type Communique struct {
	MakeMeCry *bool `protobuf:"varint,1,opt,name=make_me_cry,json=makeMeCry" json:"make_me_cry,omitempty" pg:"make_me_cry"`
	// This is a oneof, called "union".
	//
	// Types that are valid to be assigned to Union:
	//	*Communique_Number
	//	*Communique_Name
	//	*Communique_Data
	//	*Communique_TempC
	//	*Communique_Height
	//	*Communique_Today
	//	*Communique_Maybe
	//	*Communique_Delta_
	//	*Communique_Msg
	//	*Communique_Somegroup
	Union                isCommunique_Union `protobuf_oneof:"union"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Communique) Reset()         { *m = Communique{} }
func (m *Communique) String() string { return proto.CompactTextString(m) }
func (*Communique) ProtoMessage()    {}
func (*Communique) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{6}
}
func (m *Communique) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Communique.Unmarshal(m, b)
}
func (m *Communique) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Communique.Marshal(b, m, deterministic)
}
func (m *Communique) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Communique.Merge(m, src)
}
func (m *Communique) XXX_Size() int {
	return xxx_messageInfo_Communique.Size(m)
}
func (m *Communique) XXX_DiscardUnknown() {
	xxx_messageInfo_Communique.DiscardUnknown(m)
}

var xxx_messageInfo_Communique proto.InternalMessageInfo

type isCommunique_Union interface {
	isCommunique_Union()
}

type Communique_Number struct {
	Number int32 `protobuf:"varint,5,opt,name=number,oneof" json:"number,omitempty" pg:"number"`
}
type Communique_Name struct {
	Name string `protobuf:"bytes,6,opt,name=name,oneof" json:"name,omitempty" pg:"name"`
}
type Communique_Data struct {
	Data []byte `protobuf:"bytes,7,opt,name=data,oneof" json:"data,omitempty" pg:"data"`
}
type Communique_TempC struct {
	TempC float64 `protobuf:"fixed64,8,opt,name=temp_c,json=tempC,oneof" json:"temp_c,omitempty" pg:"temp_c"`
}
type Communique_Height struct {
	Height float32 `protobuf:"fixed32,9,opt,name=height,oneof" json:"height,omitempty" pg:"height"`
}
type Communique_Today struct {
	Today Days `protobuf:"varint,10,opt,name=today,enum=my.test.Days,oneof" json:"today,omitempty" pg:"today"`
}
type Communique_Maybe struct {
	Maybe bool `protobuf:"varint,11,opt,name=maybe,oneof" json:"maybe,omitempty" pg:"maybe"`
}
type Communique_Delta_ struct {
	Delta int32 `protobuf:"zigzag32,12,opt,name=delta,oneof" json:"delta,omitempty" pg:"delta"`
}
type Communique_Msg struct {
	Msg *Reply `protobuf:"bytes,16,opt,name=msg,oneof" json:"msg,omitempty" pg:"msg"`
}
type Communique_Somegroup struct {
	Somegroup *Communique_SomeGroup `protobuf:"group,14,opt,name=SomeGroup,json=somegroup,oneof" json:"somegroup,omitempty" pg:"somegroup"`
}

func (*Communique_Number) isCommunique_Union()    {}
func (*Communique_Name) isCommunique_Union()      {}
func (*Communique_Data) isCommunique_Union()      {}
func (*Communique_TempC) isCommunique_Union()     {}
func (*Communique_Height) isCommunique_Union()    {}
func (*Communique_Today) isCommunique_Union()     {}
func (*Communique_Maybe) isCommunique_Union()     {}
func (*Communique_Delta_) isCommunique_Union()    {}
func (*Communique_Msg) isCommunique_Union()       {}
func (*Communique_Somegroup) isCommunique_Union() {}

func (m *Communique) GetUnion() isCommunique_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Communique) GetMakeMeCry() bool {
	if m != nil && m.MakeMeCry != nil {
		return *m.MakeMeCry
	}
	return false
}

func (m *Communique) GetNumber() int32 {
	if x, ok := m.GetUnion().(*Communique_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Communique) GetName() string {
	if x, ok := m.GetUnion().(*Communique_Name); ok {
		return x.Name
	}
	return ""
}

func (m *Communique) GetData() []byte {
	if x, ok := m.GetUnion().(*Communique_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Communique) GetTempC() float64 {
	if x, ok := m.GetUnion().(*Communique_TempC); ok {
		return x.TempC
	}
	return 0
}

func (m *Communique) GetHeight() float32 {
	if x, ok := m.GetUnion().(*Communique_Height); ok {
		return x.Height
	}
	return 0
}

func (m *Communique) GetToday() Days {
	if x, ok := m.GetUnion().(*Communique_Today); ok {
		return x.Today
	}
	return Days_MONDAY
}

func (m *Communique) GetMaybe() bool {
	if x, ok := m.GetUnion().(*Communique_Maybe); ok {
		return x.Maybe
	}
	return false
}

func (m *Communique) GetDelta() int32 {
	if x, ok := m.GetUnion().(*Communique_Delta_); ok {
		return x.Delta
	}
	return 0
}

func (m *Communique) GetMsg() *Reply {
	if x, ok := m.GetUnion().(*Communique_Msg); ok {
		return x.Msg
	}
	return nil
}

func (m *Communique) GetSomegroup() *Communique_SomeGroup {
	if x, ok := m.GetUnion().(*Communique_Somegroup); ok {
		return x.Somegroup
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Communique) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Communique_Number)(nil),
		(*Communique_Name)(nil),
		(*Communique_Data)(nil),
		(*Communique_TempC)(nil),
		(*Communique_Height)(nil),
		(*Communique_Today)(nil),
		(*Communique_Maybe)(nil),
		(*Communique_Delta_)(nil),
		(*Communique_Msg)(nil),
		(*Communique_Somegroup)(nil),
	}
}

type Communique_SomeGroup struct {
	Member               *string  `protobuf:"bytes,15,opt,name=member" json:"member,omitempty" pg:"member"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Communique_SomeGroup) Reset()         { *m = Communique_SomeGroup{} }
func (m *Communique_SomeGroup) String() string { return proto.CompactTextString(m) }
func (*Communique_SomeGroup) ProtoMessage()    {}
func (*Communique_SomeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{6, 0}
}
func (m *Communique_SomeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Communique_SomeGroup.Unmarshal(m, b)
}
func (m *Communique_SomeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Communique_SomeGroup.Marshal(b, m, deterministic)
}
func (m *Communique_SomeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Communique_SomeGroup.Merge(m, src)
}
func (m *Communique_SomeGroup) XXX_Size() int {
	return xxx_messageInfo_Communique_SomeGroup.Size(m)
}
func (m *Communique_SomeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_Communique_SomeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_Communique_SomeGroup proto.InternalMessageInfo

func (m *Communique_SomeGroup) GetMember() string {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return ""
}

type Communique_Delta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Communique_Delta) Reset()         { *m = Communique_Delta{} }
func (m *Communique_Delta) String() string { return proto.CompactTextString(m) }
func (*Communique_Delta) ProtoMessage()    {}
func (*Communique_Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c9b60a40d5131b9, []int{6, 1}
}
func (m *Communique_Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Communique_Delta.Unmarshal(m, b)
}
func (m *Communique_Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Communique_Delta.Marshal(b, m, deterministic)
}
func (m *Communique_Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Communique_Delta.Merge(m, src)
}
func (m *Communique_Delta) XXX_Size() int {
	return xxx_messageInfo_Communique_Delta.Size(m)
}
func (m *Communique_Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Communique_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Communique_Delta proto.InternalMessageInfo

var E_Tag = &proto.ExtensionDesc{
	ExtendedType:  (*Reply)(nil),
	ExtensionType: (*string)(nil),
	Field:         103,
	Name:          "my.test.tag",
	Tag:           "bytes,103,opt,name=tag",
	Filename:      "my_test/test.proto",
}

var E_Donut = &proto.ExtensionDesc{
	ExtendedType:  (*Reply)(nil),
	ExtensionType: (*OtherReplyExtensions)(nil),
	Field:         106,
	Name:          "my.test.donut",
	Tag:           "bytes,106,opt,name=donut",
	Filename:      "my_test/test.proto",
}

func init() {
	proto.RegisterEnum("my.test.HatType", HatType_name, HatType_value)
	proto.RegisterEnum("my.test.Days", Days_name, Days_value)
	proto.RegisterEnum("my.test.Request_Color", Request_Color_name, Request_Color_value)
	proto.RegisterEnum("my.test.Reply_Entry_Game", Reply_Entry_Game_name, Reply_Entry_Game_value)
	proto.RegisterType((*Request)(nil), "my.test.Request")
	proto.RegisterMapType((map[int64]*Reply)(nil), "my.test.Request.MsgMappingEntry")
	proto.RegisterMapType((map[int32]string)(nil), "my.test.Request.NameMappingEntry")
	proto.RegisterType((*Request_SomeGroup)(nil), "my.test.Request.SomeGroup")
	proto.RegisterType((*Reply)(nil), "my.test.Reply")
	proto.RegisterType((*Reply_Entry)(nil), "my.test.Reply.Entry")
	proto.RegisterType((*OtherBase)(nil), "my.test.OtherBase")
	proto.RegisterExtension(E_ReplyExtensions_Time)
	proto.RegisterExtension(E_ReplyExtensions_Carrot)
	proto.RegisterExtension(E_ReplyExtensions_Donut)
	proto.RegisterType((*ReplyExtensions)(nil), "my.test.ReplyExtensions")
	proto.RegisterType((*OtherReplyExtensions)(nil), "my.test.OtherReplyExtensions")
	proto.RegisterType((*OldReply)(nil), "my.test.OldReply")
	proto.RegisterType((*Communique)(nil), "my.test.Communique")
	proto.RegisterType((*Communique_SomeGroup)(nil), "my.test.Communique.SomeGroup")
	proto.RegisterType((*Communique_Delta)(nil), "my.test.Communique.Delta")
	proto.RegisterExtension(E_Tag)
	proto.RegisterExtension(E_Donut)
}

func init() { proto.RegisterFile("my_test/test.proto", fileDescriptor_2c9b60a40d5131b9) }

var fileDescriptor_2c9b60a40d5131b9 = []byte{
	// 1149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x49, 0x51, 0x87, 0x91, 0x7f, 0x9b, 0xff, 0xc2, 0xb5, 0x59, 0x15, 0x49, 0x58, 0x25,
	0x2e, 0x14, 0xb7, 0x96, 0x63, 0xb5, 0x40, 0x53, 0x15, 0x2d, 0x6a, 0x1d, 0x1c, 0x07, 0xb1, 0xa5,
	0x62, 0xe3, 0x5c, 0x34, 0x37, 0x04, 0x2d, 0xad, 0x28, 0xd6, 0x5a, 0x92, 0x21, 0x97, 0x85, 0x79,
	0xe7, 0xa7, 0x68, 0x5f, 0xa3, 0xf7, 0x7d, 0x86, 0x3e, 0x93, 0x8b, 0x9d, 0x55, 0x24, 0xd9, 0x2a,
	0xca, 0x0b, 0x82, 0x33, 0xf3, 0xcd, 0x37, 0xbb, 0x33, 0xb3, 0xb3, 0x04, 0xc2, 0x73, 0x57, 0xb0,
	0x54, 0x1c, 0xc9, 0x57, 0x33, 0x4e, 0x22, 0x11, 0x91, 0x12, 0xcf, 0x9b, 0x52, 0xac, 0x11, 0x9e,
	0xcd, 0x44, 0x70, 0x84, 0xef, 0x63, 0x65, 0xac, 0xff, 0x5d, 0x84, 0x12, 0x65, 0x1f, 0x32, 0x96,
	0x0a, 0x62, 0x81, 0x71, 0xcd, 0x72, 0x5b, 0x73, 0x8c, 0x86, 0x41, 0xe5, 0x27, 0x69, 0x80, 0x31,
	0xcd, 0x98, 0x6d, 0x38, 0x5a, 0x63, 0xab, 0xb5, 0xdb, 0x9c, 0x13, 0x35, 0xe7, 0x0e, 0xcd, 0x6e,
	0x34, 0x8b, 0x12, 0x2a, 0x21, 0xe4, 0x00, 0x8c, 0xa9, 0x27, 0xec, 0x02, 0x22, 0xad, 0x05, 0xf2,
	0xcc, 0x13, 0x97, 0x79, 0xcc, 0xda, 0xc5, 0xd3, 0x7e, 0x6f, 0x48, 0x4f, 0xa8, 0x04, 0x91, 0x27,
	0x50, 0x1e, 0x33, 0x6f, 0x3c, 0x0b, 0x42, 0x66, 0x97, 0x1c, 0xad, 0xa1, 0xb7, 0x8d, 0x20, 0x9c,
	0xd0, 0x85, 0x92, 0xbc, 0x84, 0x4a, 0x1a, 0x71, 0xe6, 0x27, 0x51, 0x16, 0xdb, 0x65, 0x47, 0x6b,
	0x40, 0xab, 0xb6, 0x16, 0xfc, 0x6d, 0xc4, 0xd9, 0x2b, 0x89, 0xa0, 0x4b, 0x30, 0xe9, 0xc1, 0x66,
	0xe8, 0x71, 0xe6, 0x72, 0x2f, 0x8e, 0x83, 0xd0, 0xb7, 0xb7, 0x1c, 0xa3, 0x51, 0x6d, 0x7d, 0xbe,
	0xe6, 0x3c, 0xf0, 0x38, 0xbb, 0x50, 0x98, 0x7e, 0x28, 0x92, 0x9c, 0x56, 0xc3, 0xa5, 0x86, 0x9c,
	0x40, 0x95, 0xa7, 0xfe, 0x82, 0x64, 0x1b, 0x49, 0x9c, 0x35, 0x92, 0x8b, 0xd4, 0xbf, 0xc7, 0x01,
	0x7c, 0xa1, 0x20, 0x3b, 0x60, 0x26, 0x2c, 0x65, 0xc2, 0xde, 0x74, 0xb4, 0x86, 0x49, 0x95, 0x40,
	0xf6, 0xa0, 0xe4, 0x33, 0xe1, 0xca, 0x2c, 0x5b, 0x8e, 0xd6, 0xa8, 0xd0, 0xa2, 0xcf, 0xc4, 0x1b,
	0x96, 0x93, 0xa7, 0x00, 0x93, 0x59, 0xe4, 0x09, 0x37, 0x0c, 0xc2, 0x89, 0xbd, 0x83, 0x49, 0x29,
	0x1c, 0xca, 0xac, 0x54, 0x50, 0x3f, 0x08, 0xc2, 0x09, 0xa9, 0x7f, 0x04, 0xc5, 0x12, 0xf4, 0xc9,
	0x32, 0x73, 0x0a, 0xf3, 0xb3, 0xc2, 0x28, 0xc1, 0x65, 0x37, 0xb1, 0xbd, 0x8b, 0x10, 0xf3, 0x98,
	0x7d, 0xf9, 0xe2, 0x3b, 0x5a, 0x46, 0x7d, 0xff, 0x26, 0x26, 0xfb, 0x50, 0x1d, 0x47, 0xd9, 0xd5,
	0x8c, 0xa9, 0x68, 0x7b, 0x8e, 0xd6, 0xd0, 0xe6, 0xd1, 0x40, 0x19, 0x30, 0xdc, 0xb3, 0x05, 0x0c,
	0xe3, 0xd9, 0x08, 0x33, 0x56, 0x50, 0x18, 0xf0, 0x39, 0xcc, 0x25, 0x8c, 0xf8, 0x29, 0x82, 0xe0,
	0xf8, 0xc5, 0xc7, 0x87, 0x56, 0x94, 0xb5, 0x7f, 0x13, 0xd7, 0xbe, 0x82, 0xca, 0xa2, 0x68, 0xe4,
	0x09, 0x54, 0xb1, 0x64, 0xee, 0x24, 0x60, 0xb3, 0xb1, 0x5d, 0xc1, 0x34, 0x01, 0xaa, 0x4e, 0xa5,
	0xa6, 0xf6, 0x23, 0x58, 0x0f, 0xab, 0xb4, 0xec, 0x50, 0x09, 0xc6, 0x0e, 0xdd, 0x01, 0xf3, 0x37,
	0x6f, 0x96, 0x31, 0x5b, 0xc7, 0x7c, 0x2a, 0xa1, 0xad, 0xbf, 0xd4, 0x6a, 0x17, 0xb0, 0xfd, 0xa0,
	0x40, 0xab, 0xee, 0x44, 0xb9, 0x3f, 0x5b, 0x75, 0xaf, 0xb6, 0xb6, 0x56, 0x6a, 0x1c, 0xcf, 0xf2,
	0x15, 0xba, 0xfa, 0x3e, 0x98, 0xd8, 0xee, 0xa4, 0x04, 0x06, 0xed, 0xf7, 0xac, 0x0d, 0x52, 0x01,
	0xf3, 0x15, 0xed, 0xf7, 0x07, 0x96, 0x46, 0xca, 0x50, 0xe8, 0x9c, 0xbf, 0xeb, 0x5b, 0x7a, 0xfd,
	0x0f, 0x1d, 0x4c, 0xf4, 0x25, 0x07, 0x60, 0x4e, 0xa2, 0x2c, 0x1c, 0xe3, 0x79, 0xaa, 0xb6, 0x76,
	0xee, 0x53, 0x37, 0x55, 0xcb, 0x28, 0x08, 0xd9, 0x87, 0xcd, 0x51, 0xc4, 0x63, 0x6f, 0x84, 0xbd,
	0x91, 0xda, 0xba, 0x63, 0x34, 0xcc, 0x8e, 0x6e, 0x69, 0xb4, 0x3a, 0xd7, 0xbf, 0x61, 0x79, 0x5a,
	0xfb, 0x53, 0x03, 0x53, 0xed, 0xa4, 0x07, 0x4f, 0xae, 0x59, 0xee, 0x8a, 0xa9, 0x6c, 0x19, 0xc6,
	0xc6, 0xa9, 0x7b, 0xdc, 0xfa, 0xfa, 0x9b, 0x91, 0xc7, 0xd9, 0xcc, 0xed, 0x7a, 0xe9, 0xeb, 0xd0,
	0xb7, 0x35, 0x47, 0x6f, 0x18, 0xf4, 0xb3, 0x6b, 0x96, 0x5f, 0x4e, 0x3d, 0x31, 0x90, 0xa0, 0x05,
	0x46, 0x41, 0xc8, 0xde, 0xea, 0xee, 0x8d, 0xb6, 0xf6, 0xed, 0x7c, 0xc3, 0xe4, 0x0b, 0xb0, 0x5c,
	0x9e, 0xab, 0xd2, 0xb8, 0x78, 0xa0, 0x5a, 0x38, 0x04, 0x0c, 0xba, 0x79, 0x91, 0x63, 0x79, 0x64,
	0x69, 0x5a, 0x75, 0x07, 0x0a, 0xaf, 0x3c, 0xce, 0xc8, 0x26, 0x94, 0x4f, 0x87, 0xc3, 0xcb, 0xce,
	0xc9, 0xf9, 0xb9, 0xa5, 0x11, 0x80, 0xe2, 0x65, 0x7f, 0x30, 0x78, 0xfd, 0xd6, 0xd2, 0x0f, 0xca,
	0xe5, 0xb1, 0x75, 0x7b, 0x7b, 0x7b, 0xab, 0xd7, 0x9f, 0x43, 0x65, 0x28, 0xa6, 0x2c, 0xe9, 0x78,
	0x29, 0x23, 0x04, 0x0a, 0x92, 0x16, 0x4b, 0x51, 0xa1, 0xf8, 0xbd, 0x02, 0xfd, 0x4b, 0x83, 0x6d,
	0xcc, 0x52, 0xff, 0x46, 0xb0, 0x30, 0x0d, 0xa2, 0x30, 0x6d, 0xd5, 0xa1, 0x20, 0x02, 0xce, 0xc8,
	0x83, 0x12, 0xd9, 0x4c, 0x76, 0x1c, 0x45, 0x5b, 0xeb, 0x27, 0x28, 0x8e, 0xbc, 0x24, 0x89, 0xc4,
	0x1a, 0x2a, 0xc0, 0xf2, 0xda, 0xf7, 0xb5, 0x4b, 0x76, 0x3a, 0xf7, 0x6b, 0x75, 0xc0, 0x1c, 0x47,
	0x61, 0x26, 0x08, 0x59, 0x40, 0x17, 0x8b, 0xc6, 0x50, 0xff, 0x45, 0xa2, 0x5c, 0xeb, 0x0d, 0xd8,
	0x41, 0x9f, 0x07, 0xe6, 0xf5, 0xe6, 0xad, 0xdb, 0x50, 0x1e, 0xce, 0xc6, 0x88, 0xc3, 0xdd, 0xdf,
	0xdd, 0xdd, 0xdd, 0x95, 0xda, 0x7a, 0x59, 0xab, 0xff, 0x6e, 0x00, 0x74, 0x23, 0xce, 0xb3, 0x30,
	0xf8, 0x90, 0x31, 0xf2, 0x18, 0xaa, 0xdc, 0xbb, 0x66, 0x2e, 0x67, 0xee, 0x28, 0x51, 0x14, 0x65,
	0x5a, 0x91, 0xaa, 0x0b, 0xd6, 0x4d, 0x72, 0x62, 0x43, 0x31, 0xcc, 0xf8, 0x15, 0x4b, 0x6c, 0x53,
	0xb2, 0x9f, 0x6d, 0xd0, 0xb9, 0x4c, 0x76, 0xe6, 0x89, 0x2e, 0xca, 0x44, 0x9f, 0x6d, 0xa8, 0x54,
	0x4b, 0xed, 0xd8, 0x13, 0x1e, 0x4e, 0xdf, 0x4d, 0xa9, 0x95, 0x12, 0xd9, 0x83, 0xa2, 0x60, 0x3c,
	0x76, 0x47, 0x38, 0x73, 0xb5, 0xb3, 0x0d, 0x6a, 0x4a, 0xb9, 0x2b, 0xe9, 0xa7, 0x2c, 0xf0, 0xa7,
	0x02, 0x8f, 0xa9, 0x2e, 0xe9, 0x95, 0x4c, 0xf6, 0xc1, 0x14, 0xd1, 0xd8, 0xcb, 0x6d, 0xc0, 0xc1,
	0xff, 0xbf, 0x45, 0x6e, 0x7a, 0x5e, 0x9e, 0x22, 0x81, 0xb4, 0x92, 0x5d, 0x30, 0xb9, 0x97, 0x5f,
	0x31, 0xbb, 0x2a, 0x57, 0x2e, 0xf5, 0x28, 0x4a, 0xfd, 0x98, 0xcd, 0x84, 0x87, 0x53, 0xf2, 0xff,
	0x52, 0x8f, 0x22, 0xa9, 0x83, 0xc1, 0x53, 0x1f, 0x67, 0xe4, 0xda, 0xa1, 0x3c, 0xdb, 0xa0, 0xd2,
	0x48, 0x7e, 0x58, 0xbd, 0x24, 0xb6, 0xf0, 0x92, 0x78, 0xb4, 0x40, 0x2e, 0x73, 0xb7, 0xbc, 0x27,
	0xce, 0x36, 0x56, 0x6e, 0x8a, 0xda, 0xd3, 0xd5, 0x61, 0xb4, 0x0b, 0x45, 0xce, 0x30, 0x7f, 0xdb,
	0x6a, 0x2c, 0x2b, 0xa9, 0x56, 0x02, 0xb3, 0x27, 0x17, 0xd4, 0x29, 0x81, 0x99, 0x85, 0x41, 0x14,
	0x1e, 0x3c, 0x86, 0xd2, 0xfc, 0x4e, 0x93, 0x6d, 0xae, 0x6e, 0x35, 0x4b, 0x93, 0x43, 0xe1, 0xb4,
	0xff, 0xde, 0xd2, 0x0f, 0x9a, 0x50, 0x90, 0x5b, 0x97, 0xc6, 0x8b, 0xe1, 0xa0, 0x77, 0xf2, 0x8b,
	0xa5, 0x91, 0x2a, 0x94, 0x2e, 0xdf, 0xf5, 0xdf, 0x4a, 0x41, 0x97, 0x53, 0xe3, 0xfc, 0xdd, 0xa0,
	0xf7, 0xda, 0xd2, 0x6a, 0xba, 0xa5, 0xb5, 0x1d, 0x30, 0x84, 0xe7, 0xaf, 0xf5, 0xab, 0x8f, 0xcb,
	0x90, 0xa6, 0x76, 0xf7, 0x63, 0x4b, 0x3e, 0xc4, 0xfc, 0x8a, 0xd9, 0x79, 0x74, 0xbf, 0x51, 0xff,
	0xbd, 0x27, 0x3b, 0xdd, 0xf7, 0x27, 0x7e, 0x20, 0xa6, 0xd9, 0x55, 0x73, 0x14, 0xf1, 0x23, 0x91,
	0x44, 0xe1, 0x61, 0x96, 0x1e, 0xe1, 0x2f, 0xc0, 0x55, 0x36, 0x51, 0x1f, 0xa3, 0x43, 0x9f, 0x85,
	0x87, 0x7e, 0xe4, 0x47, 0xf8, 0xf7, 0x20, 0x5b, 0xe2, 0x68, 0xfe, 0x3b, 0xf1, 0xbd, 0x7c, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xe8, 0x5b, 0xe3, 0x5d, 0x08, 0x00, 0x00,
}
